FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_AUTH_API_URL=http://localhost:3005
ARG VITE_CORE_API_URL=http://localhost:3007
ARG VITE_NOTIFICATION_API_URL=http://localhost:3008
ARG VITE_NOTIFICATION_SOCKET_URL=http://localhost:3008
ARG VITE_CMS_API_URL=http://localhost:3009
ARG VITE_CMS_SOCKET_URL=http://localhost:3009
ARG VITE_AI_API_URL=http://localhost:3010
ARG VITE_API_DEVICE_INFO=
ARG VITE_VAPI_PUBLIC_KEY=
ARG VITE_VAPI_ASSISTANT_ID=

ENV VITE_AUTH_API_URL=$VITE_AUTH_API_URL
ENV VITE_CORE_API_URL=$VITE_CORE_API_URL
ENV VITE_NOTIFICATION_API_URL=$VITE_NOTIFICATION_API_URL
ENV VITE_NOTIFICATION_SOCKET_URL=$VITE_NOTIFICATION_SOCKET_URL
ENV VITE_CMS_API_URL=$VITE_CMS_API_URL
ENV VITE_CMS_SOCKET_URL=$VITE_CMS_SOCKET_URL
ENV VITE_AI_API_URL=$VITE_AI_API_URL
ENV VITE_API_DEVICE_INFO=$VITE_API_DEVICE_INFO
ENV VITE_VAPI_PUBLIC_KEY=$VITE_VAPI_PUBLIC_KEY
ENV VITE_VAPI_ASSISTANT_ID=$VITE_VAPI_ASSISTANT_ID

RUN npm run build

FROM nginx:1.27-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
