import { Loader2, Sparkles } from 'lucide-react';
import type { LabInterpretationView } from '@/lib/api/ai-api';
import type { TriggerLabOrderAiResponse } from '@/lib/api/lab-api';
import Badge from '@/ui/atoms/Badge';
import Button from '@/ui/atoms/Button';

export default function AIInterpretationPanel({
  loading,
  interpretationLoading,
  interpretationError,
  interpretation,
  canTrigger = true,
  result,
  onTrigger,
}: {
  loading?: boolean;
  interpretationLoading?: boolean;
  interpretationError?: boolean;
  interpretation?: LabInterpretationView | null;
  canTrigger?: boolean;
  result?: TriggerLabOrderAiResponse | null;
  onTrigger: () => void;
}) {
  const clinicalVersion = interpretation?.clinicalVersion?.trim();
  const patientVersion = interpretation?.patientVersion?.trim();
  const displayedInterpretation = clinicalVersion || patientVersion;
  const interpretationLabel = clinicalVersion ? 'Clinical interpretation' : 'AI interpretation';
  const isPreparing = !interpretationLoading && !interpretationError && !displayedInterpretation;

  return (
    <section className="space-y-3 rounded-lg border border-border bg-surface/50 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-sm font-semibold text-foreground">AI Interpretation</h3>
            <Badge variant="info">AI-Assisted</Badge>
          </div>
          <p className="mt-1 text-sm text-muted">
            {displayedInterpretation
              ? `${interpretationLabel} generated by the AI service.`
              : 'AI interpretation is queued after completion or doctor trigger.'}
          </p>
        </div>
        <Button
          type="button"
          size="sm"
          variant="secondary"
          loading={loading}
          disabled={!canTrigger}
          leftIcon={<Sparkles className="h-4 w-4" />}
          onClick={onTrigger}
        >
          Trigger AI
        </Button>
      </div>

      {result ? (
        <div className="flex flex-wrap items-center gap-2 text-sm text-muted">
          <Badge>{result.status.replaceAll('_', ' ')}</Badge>
          <span>{result.message ?? 'AI interpretation queued.'}</span>
        </div>
      ) : null}

      {(interpretationLoading && !displayedInterpretation) || isPreparing ? (
        <div className="flex items-start gap-3 rounded-lg border border-primary/15 bg-primary/5 p-3 text-sm">
          <Loader2 className="mt-0.5 h-4 w-4 animate-spin text-primary" />
          <div>
            <p className="font-medium text-foreground">AI interpretation is being prepared</p>
            <p className="mt-1 text-xs text-muted">We will keep checking for the saved interpretation.</p>
          </div>
        </div>
      ) : null}

      {interpretationError ? <p className="text-sm text-muted">AI interpretation could not be loaded right now.</p> : null}

      {displayedInterpretation ? (
        <div className="space-y-3 text-sm text-muted">
          <p>{displayedInterpretation}</p>
          {interpretation?.riskFlags?.length ? (
            <div className="flex flex-wrap gap-2">
              {interpretation.riskFlags.map((flag) => (
                <Badge key={flag} variant="warning">
                  {flag}
                </Badge>
              ))}
            </div>
          ) : null}
          {interpretation?.recommendations?.length ? (
            <div className="space-y-1">
              <p className="text-xs font-medium uppercase text-muted">Recommendations</p>
              <div className="flex flex-wrap gap-2">
                {interpretation.recommendations.map((item) => (
                  <Badge key={item}>{item}</Badge>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
